# Generated by Django 3.2.4 on 2021-12-05 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontsite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='beer',
            name='modalVal',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coffee',
            name='modalVal',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='merchandise',
            name='modalVal',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sandwhiches',
            name='modalVal',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
